### ISSUE TITLE
有关答案评估的方法

### ISSUE THREAD

**Issue by lilhongxy** [Alsace08/Chain-of-Embedding#1]
在代码库中没有看到如何对模型输出判断正确还是错误，请问是如何实现的，相关代码会release吗？
看到论文中是用 exact match，但是对于选择题模型输出的分析过程中是不是会对每个选项都进行分析

**Comment by Alsace08** [comment]
exact match 的评估代码可以在 Evaluation 文件夹中获取。对于选择题，我们目前只考虑匹配模型是否遵循了指令要求，按照正确格式输出了正确选项
